"""add buildings and upgrades

Revision ID: 36667c20c59b
Revises: bc5ff0aac48f
Create Date: 2026-01-31 20:11:52.817652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36667c20c59b'
down_revision: Union[str, Sequence[str], None] = 'bc5ff0aac48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'type', name='uq_buildings_city_type')
    )
    op.create_index(op.f('ix_buildings_city_id'), 'buildings', ['city_id'], unique=False)
    op.create_table('upgrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('building_type', sa.String(length=32), nullable=False),
    sa.Column('from_level', sa.Integer(), nullable=False),
    sa.Column('to_level', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completes_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', name='uq_upgrades_one_per_city')
    )
    op.create_index(op.f('ix_upgrades_city_id'), 'upgrades', ['city_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upgrades_city_id'), table_name='upgrades')
    op.drop_table('upgrades')
    op.drop_index(op.f('ix_buildings_city_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
