"""add raids

Revision ID: 6390ad624c9b
Revises: 0e7216d3fb36
Create Date: 2026-01-31 22:15:18.638243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6390ad624c9b'
down_revision: Union[str, Sequence[str], None] = '0e7216d3fb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_city_id', sa.Integer(), nullable=False),
    sa.Column('target_city_id', sa.Integer(), nullable=False),
    sa.Column('carry_capacity', sa.Integer(), nullable=False),
    sa.Column('stolen_food', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stolen_wood', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stolen_stone', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stolen_iron', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attacker_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['target_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raids_attacker_city_id'), 'raids', ['attacker_city_id'], unique=False)
    op.create_index(op.f('ix_raids_target_city_id'), 'raids', ['target_city_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raids_target_city_id'), table_name='raids')
    op.drop_index(op.f('ix_raids_attacker_city_id'), table_name='raids')
    op.drop_table('raids')
    # ### end Alembic commands ###
