"""add governor hero bonuses

Revision ID: 6c52a9103c97
Revises: 753ce5ebf95b
Create Date: 2026-06-24 02:25:36.127371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c52a9103c97'
down_revision: Union[str, Sequence[str], None] = '753ce5ebf95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'heroes',
        sa.Column(
           'governor_research_speed_bonus',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'heroes',
        sa.Column(
           'governor_training_speed_bonus',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'heroes',
        sa.Column(
            'governor_production_bonus',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'governor_production_bonus')
    op.drop_column('heroes', 'governor_training_speed_bonus')
    op.drop_column('heroes', 'governor_research_speed_bonus')
    # ### end Alembic commands ###
