"""add heroes table

Revision ID: 753ce5ebf95b
Revises: 1ab954595e2e
Create Date: 2026-06-23 23:30:33.086233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753ce5ebf95b'
down_revision: Union[str, Sequence[str], None] = '1ab954595e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('attack_bonus', sa.Integer(), nullable=False),
    sa.Column('defense_bonus', sa.Integer(), nullable=False),
    sa.Column('march_speed_bonus', sa.Integer(), nullable=False),
    sa.Column('training_speed_bonus', sa.Integer(), nullable=False),
    sa.Column('research_speed_bonus', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_city_id'), 'heroes', ['city_id'], unique=False)
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique=False)
#    op.alter_column('mail_messages', 'id',
#               existing_type=sa.INTEGER(),
#               nullable=False,
#               autoincrement=True)
#    op.alter_column('mail_messages', 'created_at',
#               existing_type=sa.TEXT(),
#               type_=sa.DateTime(),
#               existing_nullable=False,
#               existing_server_default=sa.text("(datetime('now'))"))
#    op.alter_column('mail_messages', 'read_at',
#               existing_type=sa.TEXT(),
#               type_=sa.DateTime(),
#                existing_nullable=True)
#    op.drop_index(op.f('idx_mail_user_created'), table_name='mail_messages')
#    op.drop_index(op.f('idx_mail_user_unread'), table_name='mail_messages')
#    op.create_index(op.f('ix_mail_messages_id'), 'mail_messages', ['id'], unique=False)
#    op.create_index(op.f('ix_mail_messages_user_id'), 'mail_messages', ['user_id'], unique=False)
#    op.alter_column('raid_defender_troops', 'id',
#                existing_type=sa.INTEGER(),
#               nullable=False,
#              autoincrement=True)
#    op.drop_index(op.f('ix_training_queue_status'), table_name='training_queue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_index(op.f('ix_training_queue_status'), 'training_queue', ['status'], unique=False)
#    op.alter_column('raid_defender_troops', 'id',
#               existing_type=sa.INTEGER(),
#               nullable=True,
#               autoincrement=True)
#    op.drop_index(op.f('ix_mail_messages_user_id'), table_name='mail_messages')
#    op.drop_index(op.f('ix_mail_messages_id'), table_name='mail_messages')
#    op.create_index(op.f('idx_mail_user_unread'), 'mail_messages', ['user_id', 'is_read', 'created_at'], unique=False)
#    op.create_index(op.f('idx_mail_user_created'), 'mail_messages', ['user_id', 'created_at'], unique=False)
#    op.alter_column('mail_messages', 'read_at',
#               existing_type=sa.DateTime(),
#               type_=sa.TEXT(),
#               existing_nullable=True)
#    op.alter_column('mail_messages', 'created_at',
#               existing_type=sa.DateTime(),
#               type_=sa.TEXT(),
#               existing_nullable=False,
#               existing_server_default=sa.text("(datetime('now'))"))
#    op.alter_column('mail_messages', 'id',
#               existing_type=sa.INTEGER(),
#               nullable=True,
#               autoincrement=True)
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_index(op.f('ix_heroes_city_id'), table_name='heroes')
    op.drop_table('heroes')
    # ### end Alembic commands ###
