"""add march speed buffs

Revision ID: 9c2e8e97abb9
Revises: 05f8e558b509
Create Date: 2026-02-01 12:46:15.054960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2e8e97abb9'
down_revision: Union[str, Sequence[str], None] = '05f8e558b509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('march_speed_pct', sa.Integer(), server_default="0", nullable=False))
    op.add_column('cities', sa.Column('return_speed_pct', sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raids', sa.Column('outbound_seconds', sa.Integer(), server_default="0", nullable=False))
    op.add_column('raids', sa.Column('return_seconds', sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###
