"""add raid outbound/return seconds

Revision ID: b1269dbd630d
Revises: 9c2e8e97abb9
Create Date: 2026-02-01 12:56:16.517794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1269dbd630d'
down_revision: Union[str, Sequence[str], None] = '9c2e8e97abb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite needs a server_default when adding NOT NULL columns,
    # and it cannot DROP DEFAULT later (no ALTER COLUMN support).
    op.add_column(
        "raids",
        sa.Column("outbound_seconds", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "raids",
        sa.Column("return_seconds", sa.Integer(), server_default="0", nullable=False),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raids', 'return_seconds')
    op.drop_column('raids', 'outbound_seconds')
    # ### end Alembic commands ###
