"""add governor building speed bonus

Revision ID: d9a19f7e555c
Revises: 6c52a9103c97
Create Date: 2026-06-24 07:35:42.474444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a19f7e555c'
down_revision: Union[str, Sequence[str], None] = '6c52a9103c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
op.add_column(
    'heroes',
    sa.Column(
        'governor_building_speed_bonus',
        sa.Integer(),
        nullable=False,
        server_default='0',
    )
)
#    op.alter_column('mail_messages', 'id',
#               existing_type=sa.INTEGER(),
#               nullable=False,
#               autoincrement=True)
#    op.alter_column('mail_messages', 'created_at',
#               existing_type=sa.TEXT(),
#               type_=sa.DateTime(),
##               existing_nullable=False,
#               existing_server_default=sa.text("(datetime('now'))"))
#    op.alter_column('mail_messages', 'read_at',
#               existing_type=sa.TEXT(),
#               type_=sa.DateTime(),
#               existing_nullable=True)
#    op.drop_index(op.f('idx_mail_user_created'), table_name='mail_messages')
#    op.drop_index(op.f('idx_mail_user_unread'), table_name='mail_messages')
#    op.create_index(op.f('ix_mail_messages_id'), 'mail_messages', ['id'], unique=False)
#    op.create_index(op.f('ix_mail_messages_user_id'), 'mail_messages', ['user_id'], unique=False)
#    op.alter_column('raid_defender_troops', 'id',
#               existing_type=sa.INTEGER(),
#               nullable=False,
#               autoincrement=True)
#    op.drop_index(op.f('ix_training_queue_status'), table_name='training_queue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_index(op.f('ix_training_queue_status'), 'training_queue', ['status'], unique=False)
#    op.alter_column('raid_defender_troops', 'id',
#               existing_type=sa.INTEGER(),
#               nullable=True,
#               autoincrement=True)
#    op.drop_index(op.f('ix_mail_messages_user_id'), table_name='mail_messages')
#    op.drop_index(op.f('ix_mail_messages_id'), table_name='mail_messages')
#    op.create_index(op.f('idx_mail_user_unread'), 'mail_messages', ['user_id', 'is_read', 'created_at'], unique=False)
#    op.create_index(op.f('idx_mail_user_created'), 'mail_messages', ['user_id', 'created_at'], unique=False)
#    op.alter_column('mail_messages', 'read_at',
#               existing_type=sa.DateTime(),
#               type_=sa.TEXT(),
#               existing_nullable=True)
#    op.alter_column('mail_messages', 'created_at',
#               existing_type=sa.DateTime(),
#               type_=sa.TEXT(),
#               existing_nullable=False,
#               existing_server_default=sa.text("(datetime('now'))"))
#    op.alter_column('mail_messages', 'id',
#               existing_type=sa.INTEGER(),
#               nullable=True,
#               autoincrement=True)
    op.drop_column('heroes', 'governor_building_speed_bonus')
    # ### end Alembic commands ###
